'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class lessons
    
    '''<summary>
    '''imgLess1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLess1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lbLess1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLess1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgLess2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLess2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lbLess2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLess2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgLess3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLess3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lbLess3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLess3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgLess4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLess4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lbLess4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLess4 As Global.System.Web.UI.WebControls.Label
End Class
